kind: pipeline
type: docker
name: default
steps:
- name: test
  image: python:3.10
  commands:
    - pip install pipenv
    - PIPENV_VENV_IN_PROJECT=1 pipenv install
    - PIPENV_VENV_IN_PROJECT=1 pipenv run python -m unittest -v
- name: docker
  image: plugins/docker
  settings:
    registry: https://gitea.petrovic.network
    repo: gitea.petrovic.network/adampetrovic/pvoutput-tariff
    auto_tag: true
    username: adampetrovic
    password:
      from_secret: GITEA_DOCKER