kind: pipeline
type: docker
name: default
steps:
- name: test
  image: python:3.10
  commands:
    - pipenv install
    - pipenv run python -m unittest
- name: docker
  image: plugins/docker
  settings:
    registry: https://gitea.petrovic.network
    repo: gitea.petrovic.network/adampetrovic/pvoutput-tariff
    auto_tag: true
    username: adampetrovic
    password:
      from_secret: GITEA_DOCKER